# Generated by Django 6.0.6 on 2026-08-11 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_entry_level_and_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_headed', to=settings.AUTH_USER_MODEL),
        ),
    ]
