# Generated by Django 6.0.6 on 2026-08-16 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_admissionrecord_add_pin_to_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_type',
            field=models.CharField(choices=[('UTME', 'UTME (Regular Entry)'), ('DE', 'Direct Entry'), ('TRANSFER_INTRA', 'Transfer (Intra-Faculty)'), ('TRANSFER_INTER', 'Transfer (Inter-Faculty)')], default='UTME', max_length=20),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dean', models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Dean'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_headed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'faculties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='students.faculty'),
        ),
    ]
