# Generated by Django 6.0.6 on 2026-08-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_admission_type_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='duration_years',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 Years'), (4, '4 Years'), (5, '5 Years'), (6, '6 Years')], default=4),
        ),
    ]
