"""
Django settings for lu_sims project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as messages
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original insecure dev key so local runserver/tests need no .env -
# a real deployment must set SECRET_KEY in .env (see .env.example).
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-txl2yz#4y0)di(3ug_n$%oosait2_ep(3*jbq)t$lptg1t29=e')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True (unchanged local-dev behavior with no .env) - a real deployment
# must set DEBUG=False in .env.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Comma-separated in .env, e.g. ALLOWED_HOSTS=lu-sims.example.com,www.lu-sims.example.com.
# Empty is fine for local dev - Django auto-allows localhost/127.0.0.1 while DEBUG=True.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'students',
    'courses',
    'results',
]

AUTH_USER_MODEL = 'accounts.User'

# Only LenientUsernameBackend - it already extends ModelBackend (inherits
# has_perm/get_all_permissions unchanged), so it's a strict superset for
# authentication purposes. A second, separate ModelBackend entry here would let
# Django silently fall through to it whenever the first backend returns None,
# bypassing the FR-AUTH-05 login lockout entirely for exact-username logins.
AUTHENTICATION_BACKENDS = [
    'accounts.auth_backends.LenientUsernameBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Initial password for every created account - students via Add Student/Bulk Import
# (Registrar), staff via Manage Staff (IT Admin) or Django admin. Forced change on first
# login (students also need the PIN emailed to them at creation time - see
# StudentProfile.pin_hash).
# Bump this every academic year, e.g. 'lu2027' for the 2027 intake.
DEFAULT_PASSWORD = 'lu2026'

# University prefix embedded in generated staff IDs (e.g. 'LU-RG-26-0001') - a settings
# constant rather than hardcoded so a future multi-institution deployment only needs to
# change this, not the ID-generation code itself.
UNIVERSITY_ABBREVIATION = 'LU'

# How often someone can change their self-service preferred_username (accounts.models.
# User.preferred_username_locked_until).
PREFERRED_USERNAME_COOLDOWN_DAYS = 7

# How often someone can change their login email (accounts.models.User.email_locked_until) -
# a separate named setting from PREFERRED_USERNAME_COOLDOWN_DAYS even though currently
# equal, so the two can be tuned independently later.
EMAIL_CHANGE_COOLDOWN_DAYS = 7

# Academic session students register courses under. Bump this every academic year,
# e.g. '2026/2027' for the next intake.
CURRENT_SESSION = '2025/2026'

# Semester students register courses under. Flip this by hand between 'first' and
# 'second' at each actual semester changeover (twice a year, unlike CURRENT_SESSION).
CURRENT_SEMESTER = 'first'

# NUC's mandated credit-unit range per semester (excludes project/thesis semesters,
# which this system doesn't model separately). MAX is enforced as a hard block on
# every registration - exceeding it is never valid. MIN is enforced as a heads-up
# warning rather than a block, since this system has no "finalize registration" step -
# a student legitimately builds up to their full load across more than one visit.
MIN_SEMESTER_UNITS = 15
MAX_SEMESTER_UNITS = 24

# Defaults to the console backend (prints instead of sending) unless real SMTP settings
# are supplied via .env - see .env.example. Nothing here changes local dev behavior until
# a .env is deliberately created with real values for an actual deployment.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'lu_sims.mail_backends.ReadableConsoleEmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@lu-sims.local')

# Forgot-password reset links expire after 1 hour - tighter than Django's 3-day
# default, since the link is effectively a bearer credential for the account.
PASSWORD_RESET_TIMEOUT = 3600

# PIN policy for the first-login identity check (students.models.StudentProfile) - lock
# the account out of retrying after this many wrong PIN attempts, for this long, to
# resist brute-forcing a 6-digit PIN.
PIN_MAX_ATTEMPTS = 5
PIN_LOCKOUT_MINUTES = 15

# Same lockout policy, for the email-change verification code (accounts.models.User) -
# same values as PIN_MAX_ATTEMPTS/PIN_LOCKOUT_MINUTES, kept as its own setting since
# accounts can't import the students-side one (see accounts.models.User docstring).
EMAIL_CHANGE_CODE_MAX_ATTEMPTS = 5
EMAIL_CHANGE_CODE_LOCKOUT_MINUTES = 15

# FR-AUTH-05: lock a portal account out after this many consecutive wrong-password
# attempts, for this long - same values/shape as the PIN and email-change lockouts,
# resisting a brute-force password guess against a known username.
LOGIN_MAX_ATTEMPTS = 5
LOGIN_LOCKOUT_MINUTES = 15

# FR-AUTH-06: log a session out after this many minutes of no activity - protects
# whoever forgets to click "Log out" on a shared/cybercafe computer. SESSION_COOKIE_AGE
# is Django's own session-lifetime setting (in seconds); SESSION_SAVE_EVERY_REQUEST
# makes it a sliding/idle timeout rather than a fixed one - every request re-saves
# the session and resets its expiry clock, so it's 15 minutes of inactivity, not
# 15 minutes total regardless of activity.
SESSION_IDLE_TIMEOUT_MINUTES = 15
SESSION_COOKIE_AGE = SESSION_IDLE_TIMEOUT_MINUTES * 60
SESSION_SAVE_EVERY_REQUEST = True

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lu_sims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lu_sims.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# HTTPS/cookie hardening - gated behind "not DEBUG" rather than applied unconditionally,
# since forcing SSL redirects and secure-only cookies would break plain-HTTP local
# runserver. Only takes effect once a real deployment sets DEBUG=False in .env.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# The default four validators only cover length/similarity/common-password/all-numeric -
# ComplexityValidator (accounts/validators.py) adds the upper/lower/digit/symbol mix on
# top, since that's what's actually enforced when a student sets their own password.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.ComplexityValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
