# Generated by Django 6.0.6 on 2026-08-12 17:03

from django.db import migrations, models


def seed_staff_id_counter(apps, schema_editor):
    # Seeded here (pk=1) rather than get_or_create-on-first-use, so
    # accounts.services.generate_next_staff_id() can assume the row always exists and
    # just select_for_update().get(pk=1) it - no first-ever-creation race to handle.
    StaffIDCounter = apps.get_model('accounts', 'StaffIDCounter')
    StaffIDCounter.objects.create(pk=1, last_number=0)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_admin_and_formalize_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(seed_staff_id_counter, migrations.RunPython.noop),
    ]
