# Generated by Django 6.0.6 on 2026-08-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_registrar_bursar_dean_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffIDCounter',
        ),
    ]
