# Generated by Django 6.0.6 on 2026-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_staffidcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=2)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('role_code', 'year')},
            },
        ),
    ]
