# Generated by Django 6.0.6 on 2026-08-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staffidsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
