from datetime import timedelta

from accounts.models import HOD_GROUP
from django.conf import settings
from django.contrib.auth.hashers import check_password, make_password
from django.db import models
from django.utils import timezone

LEVEL_CHOICES = [
    (100, "100 Level"),
    (200, "200 Level"),
    (300, "300 Level"),
    (400, "400 Level"),
    (500, "500 Level"),
]

GENDER_CHOICES = [
    ("M", "Male"),
    ("F", "Female"),
]


class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    hod = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="department_headed",
        limit_choices_to={"groups__name": HOD_GROUP},
    )

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class StudentProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="student_profile",
    )
    matric_number = models.CharField(max_length=20, unique=True)
    department = models.ForeignKey(Department, on_delete=models.PROTECT, related_name="students")
    # Level and session the student joined at - never updated after creation. Current level
    # is derived from these (see current_level below) rather than stored, so it advances on
    # its own every time settings.CURRENT_SESSION is bumped for a new academic year.
    entry_level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES)
    entry_session = models.CharField(max_length=9, help_text="e.g. 2025/2026")
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.matric_number = self.matric_number.strip().upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.matric_number} - {self.user.get_full_name() or self.user.username}"

    @property
    def current_level(self):
        entry_year = int(self.entry_session.split("/")[0])
        current_year = int(settings.CURRENT_SESSION.split("/")[0])
        years_elapsed = current_year - entry_year
        return min(self.entry_level + years_elapsed * 100, LEVEL_CHOICES[-1][0])

    @property
    def current_level_display(self):
        return dict(LEVEL_CHOICES).get(self.current_level, self.current_level)


class AdmissionRecord(models.Model):
    """A pre-seeded, not-yet-a-student admission slot, awaiting self-registration.

    IT Admin seeds these ahead of a cohort (see students.services.seed_admission_record)
    from data the registrar already assigned - matric numbers are never generated by this
    system. A student proves they're the rightful owner by matric number + PIN (see
    accounts self-registration views), then this record is consumed and deleted once the
    real User/StudentProfile is created - see set_pin/check_pin and the attempt-tracking
    fields below.
    """

    matric_number = models.CharField(max_length=20, unique=True)
    department = models.ForeignKey(Department, on_delete=models.PROTECT, related_name="admission_records")
    entry_level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(
        help_text="Admission-application email the PIN was sent to - becomes the "
                   "student's portal login email too, since self-registration doesn't "
                   "ask for a separate one."
    )
    pin_hash = models.CharField(max_length=128)
    failed_attempts = models.PositiveSmallIntegerField(default=0)
    locked_until = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.matric_number = self.matric_number.strip().upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.matric_number} - {self.first_name} {self.last_name}"

    def set_pin(self, raw_pin):
        # Hashed with the same machinery as user passwords (make_password/check_password
        # work on any string, not just User.password) - a PIN is a secret too, so it
        # never gets stored in plain text any more than a password would.
        self.pin_hash = make_password(raw_pin)

    def check_pin(self, raw_pin):
        return check_password(raw_pin, self.pin_hash)

    @property
    def is_locked(self):
        return self.locked_until is not None and self.locked_until > timezone.now()

    def register_failed_pin_attempt(self):
        self.failed_attempts += 1
        if self.failed_attempts >= settings.PIN_MAX_ATTEMPTS:
            self.locked_until = timezone.now() + timedelta(minutes=settings.PIN_LOCKOUT_MINUTES)
        self.save(update_fields=["failed_attempts", "locked_until"])

    def reset_pin_attempts(self):
        self.failed_attempts = 0
        self.locked_until = None
        self.save(update_fields=["failed_attempts", "locked_until"])
